**The hypothesis**
$$h_{\theta}(X)=Xθ$$

**The cost function**
$$J(θ)=\frac{1}{2m}(Xθ-Y)^{T}(Xθ-Y)$$

**Derivatives**
$$∇J(θ)=\frac{1}{m}X^T(Xθ-Y)$$

**Gradient descent**
$$θ ← θ-α∇J(θ)$$

*Note* :

We should not forget to add vector of ones to $X$ 




In [ ]:
import pandas as pd
import numpy as np

Linear regression oriented object implementation

In [159]:
class LinearRegression:
  # The parmeters and the error will be returned
  
  def __init__(self):
    self.__train_cost = None
    self.__theta = None

  def __preprocess(self, X, y=None, y_pre=True):
    # reshape X_train and y_train if it's necessary
    if y_pre:
      y = y.reshape((X.shape[0], 1))

    if X.size == X.shape[0]:
      X = X.reshape((X.size, 1))

    # Add column of ones to X_train
    ones = np.ones((X.shape[0], 1))
    X = np.hstack((ones, X))

    if y_pre:
      return X, y
    else:
      return X

  def __cost_function(self, X, y, theta):
    m = X.shape[0]
    error = np.subtract(np.matmul(X, theta), y)
    J = np.divide(np.matmul(error.T, error), m)[0][0]
    gradients = 2*np.divide(np.matmul(X.T, error), m)
    
    return J, gradients

  def fit(self, X_train, y_train, epochs, lr=0.01):
    # reshape X_train and y_train if it's necessary
    X_train, y_train = self.__preprocess(X_train, y_train)

    # Get the shape of the matrix X_train
    m, n = X_train.shape

    # Initialize the parameters theta
    self.__theta = np.random.rand(n, 1)


    # Run gradient descent
    for i in range(epochs):
      self.__train_cost, gradients = self.__cost_function(X_train, y_train, self.__theta)
      self.__theta -= lr*gradients



  def eval(self, X_val, y_val):
    X_val, y_val = self.__preprocess(X_val, y_val)


    y_pred = np.matmul(X_val, self.__theta)
    m = X_val.shape[0]
    eval_cost = np.divide(np.matmul((y_pred-y_val).T, y_pred-y_val), m)[0, 0]

    mean = np.mean(y_val)
    SSres = np.matmul((y_val-y_pred).T, y_val-y_pred)
    SStot = np.matmul((y_val-mean).T, y_val-mean)
    R2 = 1-SSres/SStot

    return R2[0, 0], eval_cost
  
  def predict(self, X_test):
    X_test = self.__preprocess(X_test, y_pre=False)

    return np.matmul(X_test, self.__theta)

  # getters
  @property
  def get_params(self):
    return self.__theta

  @property
  def get_cost(self):
    return self.__train_cost

In [164]:
# Create X_train, y_train
X_train = np.array([1, 2, 3, 4, 6, 7])
y_train = 3*X_train+1+np.random.rand(X_train.shape[0])
y_train

array([ 4.6033857 ,  7.6504612 , 10.98348038, 13.32988153, 19.40064801,
       22.86781212])

In [148]:
# Fit the model
model = LinearRegression()
model.fit(X_train, y_train, 2000, lr=0.01)

In [165]:
# Get the parameters and the cost
model.get_params, model.get_cost

(array([[1.56365948],
        [3.00341361]]), 0.08365080923986319)

In [150]:
# Create X_val and y_val
X_val = np.array([10, 23, 15, 14, 17, 20])
y_val = 3*X_val+1+np.random.rand(X_val.shape[0])

In [151]:
# Evaluate our model
R2, val_cost = model.eval(X_val, y_val)
R2, val_cost

(0.9991272619280405, 0.1405086663945955)

In [153]:
# Make predictions
X_test = np.array([55, 56, 12, 76.4])
model.predict(X_test)

array([[166.7514081 ],
       [169.75482171],
       [ 37.60462282],
       [231.02445938]])